/* =========================================================
   SUMMARY OF DISCONTINUED PRODUCTS BY CATEGORY
   ========================================================= */
SELECT
    c.category_name,
    COUNT(
        CASE
            WHEN p.discontinued IS TRUE THEN p.product_id
        END
    ) AS count_discontinued,
    COUNT(p.product_id) AS count_all,
    ROUND(
        COUNT(
            CASE
                WHEN p.discontinued IS TRUE THEN p.product_id
            END
        ) / CAST(COUNT(p.product_id) AS DECIMAL) * 100,
        2
    ) AS percentage_discontinued
FROM products AS p
LEFT JOIN categories AS c
    ON p.category_id = c.category_id
GROUP BY c.category_name;


/* =========================================================
   ORDERS PROCESSED BY EACH EMPLOYEE IN 2017
   ========================================================= */
WITH cte AS (
    SELECT
        COUNT(*) AS total_order_count
    FROM orders
    WHERE EXTRACT(YEAR FROM order_date) = 2017
)

SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    COUNT(*) AS order_count,
    ROUND(
        COUNT(*) / cte.total_order_count::DECIMAL * 100,
        2
    ) AS order_count_percentage
FROM cte,
     orders AS o
LEFT JOIN employees AS e
    ON o.employee_id = e.employee_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2017
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name,
    cte.total_order_count;


/* =========================================================
   REVENUE BY COUNTRY (2017)
   ========================================================= */
WITH cte AS (
    SELECT
        SUM(oi.unit_price * oi.quantity) AS total_revenue
    FROM order_items AS oi
    LEFT JOIN orders AS o
        ON oi.order_id = o.order_id
    WHERE EXTRACT(YEAR FROM o.shipped_date) = 2017
)

SELECT
    o.ship_country,
    SUM(oi.unit_price * oi.quantity) AS revenue,
    ROUND(
        SUM(oi.unit_price * oi.quantity)
        / cte.total_revenue::DECIMAL * 100,
        2
    ) AS revenue_percentage
FROM cte,
     order_items AS oi
LEFT JOIN orders AS o
    ON oi.order_id = o.order_id
WHERE EXTRACT(YEAR FROM o.shipped_date) = 2017
GROUP BY
    o.ship_country,
    cte.total_revenue
ORDER BY
    SUM(oi.unit_price * oi.quantity) DESC;


/* =========================================================
   REVENUE GENERATED BY MEXICO VS OTHER COUNTRIES
   ========================================================= */
WITH cte AS (
    SELECT
        o.customer_id,
        CASE
            WHEN c.country = 'Mexico' THEN 'Mexico'
            ELSE 'Other'
        END AS customer_country,
        o.order_id,
        SUM(
            oi.unit_price * oi.quantity * (1 - oi.discount)
        ) AS total_per_order
    FROM orders AS o
    LEFT JOIN customers AS c
        ON o.customer_id = c.customer_id
    LEFT JOIN order_items AS oi
        ON o.order_id = oi.order_id
    GROUP BY
        o.customer_id,
        c.region,
        CASE
            WHEN c.country = 'Mexico' THEN 'Mexico'
            ELSE 'Other'
        END,
        o.order_id
)

SELECT
    customer_country,
    ROUND(SUM(total_per_order), 2) AS discount_revenue
FROM cte
GROUP BY customer_country;
